default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("INVENTORY_SYSTEM_DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("INVENTORY_SYSTEM_DATABASE_PORT", "5432") %>
  username: <%= ENV.fetch("INVENTORY_SYSTEM_DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("INVENTORY_SYSTEM_DATABASE_PASSWORD", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: inventory_system_development
  queue:
    <<: *default
    database: inventory_system_development_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: inventory_system_test<%= ENV['TEST_ENV_NUMBER'] %>
  queue:
    <<: *default
    database: inventory_system_test<%= ENV['TEST_ENV_NUMBER'] %>_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: inventory_system_production
  queue:
    <<: *primary_production
    database: inventory_system_production_queue
    migrations_paths: db/queue_migrate
